[package]
name = "vpower"
version = "1.5.1"
edition = "2021"

[[bin]]
name = "vpower"
path = "main.rs"

[dependencies]
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
lazy_static = "1.5.0"
